# Generated by Django 4.2.6 on 2023-10-10 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField()),
                ('salud', models.CharField(max_length=100)),
                ('cantPeces', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FamiliaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Piscigranja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('tamano', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rol', to='aplicacion.rol')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioXPiscigranja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPiscigranja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioXPiscigranja', to='aplicacion.piscigranja')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioXPiscigranja', to='aplicacion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialNocivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('familiaMaterial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_nocivo', to='aplicacion.familiamaterial')),
            ],
        ),
        migrations.CreateModel(
            name='EstanqueMatNoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('idEstanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estanque_matnoc', to='aplicacion.estanque')),
                ('idMaterialNoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estanque_matnoc', to='aplicacion.materialnocivo')),
            ],
        ),
        migrations.AddField(
            model_name='estanque',
            name='piscigranja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estanque', to='aplicacion.piscigranja'),
        ),
    ]
