# Generated by Django 4.2.6 on 2023-10-08 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estanque',
            fields=[
                ('idestanque', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estadoSalud', models.CharField(max_length=100)),
                ('cantidadPeces', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idmaterial', models.AutoField(primary_key=True, serialize=False)),
                ('nombrematerial', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PsciGranja',
            fields=[
                ('idpscigranja', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('tamano', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idestanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.estanque')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('UsuarioID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreUsuario', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Contrasena', models.CharField(max_length=50)),
                ('Rol', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAlimentacion',
            fields=[
                ('id_registro_alimentacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo_alimento', models.CharField(max_length=100)),
                ('cantidad_alimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idpscigranja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.pscigranja')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialesEstanque',
            fields=[
                ('idMaterialesPiscigranja', models.AutoField(primary_key=True, serialize=False)),
                ('idestanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.estanque')),
                ('idmaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.material')),
            ],
        ),
    ]
