# Generated by Django 4.2.6 on 2023-11-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialnocivo',
            name='descripcion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
