# Generated by Django 4.2.6 on 2023-11-23 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_materialnocivo_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialnocivo',
            old_name='familiaMaterial',
            new_name='familiamaterial',
        ),
    ]
