# Generated by Django 4.1.6 on 2023-11-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_usuario_ciudad_usuario_pais_usuario_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
