# Generated by Django 4.1.6 on 2023-11-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_usuario_ciudad_alter_usuario_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default='0000', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.CharField(default='0000', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nruc',
            field=models.CharField(default='0000', max_length=100),
        ),
    ]
