# Generated by Django 4.1.6 on 2023-11-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_usuario_direccion_usuario_empresa_usuario_nruc'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nruc', models.CharField(max_length=50)),
                ('nombre_compañia', models.CharField(max_length=50)),
                ('direccion_sede', models.CharField(max_length=50)),
                ('numero_telefono', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
    ]
