# Generated by Django 4.1.6 on 2023-11-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ciudad_personal',
            field=models.CharField(default='0000', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pais_personal',
            field=models.CharField(default='0000', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono_personal',
            field=models.CharField(default='0000', max_length=100),
        ),
    ]
