# Generated by Django 4.1.6 on 2023-11-29 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_usuario_ciudad_personal_usuario_pais_personal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piscigranja',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='piscigranja_set', to='aplicacion.usuario'),
            preserve_default=False,
        ),
    ]
